name: find_dropdown
description: Simple and robust FindDropdown with item search feature, making it possible to use an offline item list or filtering URL for easy customization.
version: 0.2.0
author: F-Team <david@flutterando.com.br>
homepage: https://flutterando.com.br/
git: https://github.com/davidsdearaujo/find_dropdown
repository: https://github.com/davidsdearaujo/find_dropdown

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  rxdart: ">=0.23.0 <0.25.0"
  select_dialog: ^1.1.0
  # select_dialog: 
  #   git:
  #     url: https://github.com/davidsdearaujo/select_dialog.git
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
